### ISSUE TITLE
Should we add a variant built by non-webpack module bundler?

### ISSUE THREAD

**Issue by tetsuharuohzeki** [WebKit/Speedometer#102]
Webpack is still one of the popular module bundler in JavaScript ecosystem. But some other tools also emerges.

For example, there is a [rollup](https://github.com/rollup/rollup). Rollup is not only used as standalone tool, it' also used as [vite](https://github.com/vitejs/vite)'s backend.

[rollup emit a code that all modules are flatten](https://rollupjs.org/repl/) by analyzing a module graph deeply. This is contrast to webpack wraps each modules by function as a emulate a module scope.

I'm not sure about that whether JSVM has already optimized about that this kind of a code emitted by rollup. However, in today's web application size, their flatten code including many variables might have some impacts related to web browser's page initialize performance.

I don't think we should drop webpack variant but I also think it might be better to add more module linker variants to get a chance to improve more workloads.

**Comment by flashdesignory** [comment]
This is a great discussion point. 
The initial goal of the todoMVC workload updates is to introduce some consistency between the workloads, to be able to determine impact of frameworks / libraries on performance. 

Currently the todoMVC workloads use a variety of module bundlers and it makes it harder to compare. 
I do agree that it would be useful to determine if bundlers have impact, for example a react workload built with webpack vs a react workload built with rollup, parcel or any other bundler. 

This could potentially also be an iteration, once the initial updates have landed?

cc: @kara @housseindjirdeh

**Comment by rniwa** [comment]
Note that we specifically don't want to able to compare different frameworks' performances. That is specifically a non-goal.

**Comment by tetsuharuohzeki** [comment]
> Note that we specifically don't want to able to compare different frameworks' performances. That is specifically a non-goal.

Yes. I opened this issue to discuss about to complement more variants of typical web application workload in today.

**Comment by bgrins** [comment]
FWIW the new rich editor workloads from #81 are using Vite/Rollup. Also when prototyping some changes to todo workloads I found Parcel helpful (though this isn't part of the actual work that's going to land).

I would be curious to learn if the compiled code from these different tools actually have a strong Speedometer-measurable effect. Given that we start measuring after the page and all scripts are loaded my assumption is no - and that we shouldn't create permutations of workloads just to isolate that component - but it wouldn't hurt to check.

**Comment by julienw** [comment]
The new svelte implementation also uses rollup.

**Comment by julienw** [comment]
The proposed charting workload uses vite/rollup as well.

**Comment by rniwa** [comment]
Sounds like this is taken care of now. Is there anything else we should discuss before closing this issue?

**Comment by tetsuharuohzeki** [comment]
I don't have any additional topic. Thank you for your discussion.

**Comment by rniwa** [comment]
Closing the issue as complete since we have workloads that use vite/rollup now.
