### ISSUE TITLE
iterationCount should probably be able to be 1 

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#107]
We currently don't allow `<= 1` (https://github.com/WebKit/Speedometer/blob/6c31329c83815ebb55c0f2cece170a2985b77afc/resources/params.mjs#L31). Obviously niche, but I was just wanting to test a single iteration run to compare with normal runs. @camillobruni is there a reason to prevent 1?

**Comment by rniwa** [comment]
I guess standard deviation, etc... calculation need to be skipped if the iteration count is 1?

**Comment by camillobruni** [comment]
Let me add a PR, I've been wanting single iterations for quick testing as well :)
