### ISSUE TITLE
Consider adding a viewport meta tag to the runner

### ISSUE THREAD

**Issue by julienw** [WebKit/Speedometer#130]
Currently the runner doesn't have a viewport meta tag (this is true for both [index.html](https://github.com/WebKit/Speedometer/blob/main/index.html) and [InteractiveRunner.html](https://github.com/WebKit/Speedometer/blob/main/InteractiveRunner.html). Because of that, the benchmarks don't work the same on browsers on mobile. Indeed the behavior of browsers isn't the same on mobile when no meta viewport tag is present.

I'd be happy to write a patch if there's a consensus.

**Comment by rniwa** [comment]
You mean `<meta name="viewport" content="width=device-width, initial-scale=1">`?

**Comment by julienw** [comment]
Yes, exactly!

I tried this locally already: then the results are similar in chrome and firefox on Android (Ican't test safari)
But on mobile phones there's an issue that the iframe do not fit the window anymore. We might need to set some additional max-width here and there, but I'm not sure this would be enough.

**Comment by rniwa** [comment]
We'd probably need to adjust the size of iframe if we're doing this.

**Comment by rniwa** [comment]
Marking this as a v3 blocker since we need to make sure the benchmark runs fine on mobile browsers at minimum.
