### ISSUE TITLE
TodoMVC - uuid functions inconsistent

### ISSUE THREAD

**Issue by flashdesignory** [WebKit/Speedometer#136]
We are using at least two different variations of functions to create unique ids for the todomvc workloads. 
One implementation uses `crypto.randomUUID();`

As pointed out [here](https://github.com/WebKit/Speedometer/pull/134), this version might have some issues (note from Julien):
"I noticed recently that this isn't working when accessing the app using http on the network, for example when testing from Android to a local dev server."

Ideally, we clean up the usage and only use a function that works universally the same in all todomvc workloads.

**Comment by jrmuizel** [comment]
Why does the key need to universally unique? Wouldn't an incrementing number be sufficient?

**Comment by bgrins** [comment]
>  that incrementing a number performed worse than creating a unique string.

That's interesting, and potentially something that should be optimized. Can you share more about that?

There may be some benefits to having a diversity of ways to construct these (i.e. the Svelte regexp one performs quite differently than others, and you note the difference with simple incrementing). Ofc it's tricky because it's somewhat random which tests will change in which ways as a result, and also hard to quantify what are the most common ways to do something like this in the wild. Blindly copying whatever the upstream chose to do (as long as there aren't bugs/problems with running it locally) may not be the worst idea. Curious for other's opinions.

**Comment by flashdesignory** [comment]
@bgrins - so far this was strictly an observation and I didn't have the chance yet to dive into the underlying reasons. This might be framework specific in some cases and not an overall performance impact. 

I'm torn, if it makes sense to use the same uuid function for every workload or if it should be framework specific. 
On one hand it would be nice to have similar conditions as much as possible, to actually see the benefits of the various frameworks. On the other hand it would also be nice to have a variety of implementations to test. 

I think potential next steps would be to take a few workloads and benchmark some solutions, for example

- increasing number
- string + increasing number
- generic uuid function
- svelte's example of the uuid function
- some popular npm solutions?

I would probably  time-box it though and then report back with some initial findings to discuss next steps.

**Comment by julienw** [comment]
The goal for this project is not to evaluate the frameworks with each other. Therefore IMO it's OK that there can be more differences than just the frameworks in the various implementetions. So my preference would be to have different implementations of the id function.

I'm also curious to understand how an incremented integer would perform worse than a string.replace call :-)

**Comment by rniwa** [comment]
We've hit the issue of `crypto.randomUUID` not being available on non-secure context in our lab automation was well. Having diverse ways of generating IDs is good but perhaps we should stick to APIs that are universally available.

**Comment by rniwa** [comment]
Tracking the issue that the benchmark doesn't run in a HTTP server as https://github.com/WebKit/Speedometer/issues/163.

**Comment by flashdesignory** [comment]
@rniwa  - with the removal of the usage (https://github.com/WebKit/Speedometer/pull/168) and the addition of alternative solutions (https://github.com/WebKit/Speedometer/pull/211), is this good to close?

**Comment by rniwa** [comment]
Yeah, I think we can consider this fixed now.
