### ISSUE TITLE
Running with iterationCount=200 stops after 100 iterations

### ISSUE THREAD

**Issue by mstange** [WebKit/Speedometer#138]
I've been trying to gather profiles with lots of samples by repeating the test many times, but the suite appears to get stuck after 100 iterations.

Steps to reproduce:

 1. Run `npm run dev`
 2. Go to http://127.0.0.1:7000/?suite=TodoMVC-JavaScript-ES5&iterationCount=200
 3. Click "Start Test"

Expected results:
The test should run all the way to completion.

Actual results:
After 100 iterations, the test pauses and the progress bar is stuck at 50%. The results page is never shown.

**Comment by mstange** [comment]
An error appears on the console after the 100th iteration:

```
Uncaught (in promise) ReferenceError: deltas is not defined
    confidenceIntervalDelta http://127.0.0.1:7001/resources/statistics.mjs:74
    computeAggregatedMetrics http://127.0.0.1:7001/resources/metric.mjs:84
    _appendIterationMetrics http://127.0.0.1:7001/resources/benchmark-runner.mjs:318
    _finalize http://127.0.0.1:7001/resources/benchmark-runner.mjs:270
    _runAllSuites http://127.0.0.1:7001/resources/benchmark-runner.mjs:188
    runMultipleIterations http://127.0.0.1:7001/resources/benchmark-runner.mjs:169
    startBenchmark http://127.0.0.1:7001/resources/main.mjs:50
    _startBenchmarkHandler http://127.0.0.1:7001/resources/main.mjs:243
```

Thrown while evaluating the string in this throw statement:

https://github.com/WebKit/Speedometer/blob/05b6f7a08db2d8465299337f286e38e516cd9feb/resources/statistics.mjs#L71-L74

**Comment by rniwa** [comment]
Yeah, we don't support beyond 100 iterations in those statistics functions.

**Comment by bgrins** [comment]
> Yeah, we don't support beyond 100 iterations in those statistics functions.

How hard is that to change? I'm not familiar with those functions.

**Comment by rniwa** [comment]
> > Yeah, we don't support beyond 100 iterations in those statistics functions.
> 
> How hard is that to change? I'm not familiar with those functions.

It's not that hard since it's just a giant table of values of t-distribution. Someone just need to launch R/SAS/etc... and generate more values & hard code them. Having said that, I'm not certain supporting 100+ iterations is really necessary. We could just opt to check the number of iterations and omit confidence interval when there are more than 100+, or alternatively, we could always pick the last value (for 101 degrees of freedom) since values converge for large n.

**Comment by bgrins** [comment]
I haven't researched this at all but I would have thought these statistics could be calculated at runtime - I'm curious why it requires a static table?

I know @mstange had a use case for profiling very large iteration counts, so perhaps just omitting confidence intervals for > the length of the table as you suggest is the easiest path to unblock.

**Comment by rniwa** [comment]
> I haven't researched this at all but I would have thought these statistics could be calculated at runtime - I'm curious why it requires a static table?

In theory, yes. Certainly programs like R supports that. I just didn't feel like porting that code from R to JS.

**Comment by mstange** [comment]
> I know @mstange had a use case for profiling very large iteration counts, so perhaps just omitting confidence intervals for  the length of the table as you suggest is the easiest path to unblock.

That sounds great, in my use case I'm not interested in the numbers or statistics at all, I just want the test workload to run.
