### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RamiSJ12** [WebKit/Speedometer#15]
I am running the npm in vsc but no results.
![Screenshot (147)](https://user-images.githubusercontent.com/89670401/188313765-910b20c8-f842-4545-a049-c9151e0cdfc4.png)

**Comment by rniwa** [comment]
I don't understand what this issue is about. You open JSC and what happens or doesn't happen?

**Comment by RamiSJ12** [comment]
I want to run this app I developed it by - `React.JS so I used to run it by `npm` run or `npm start run` and used to work by opening chrome browser, now it's only like that see the terminal please

**Comment by rniwa** [comment]
This is not an appropriate venue to ask that kind of question.
