### ISSUE TITLE
Remove non-inclusive language

### ISSUE THREAD

**Issue by annevk** [WebKit/Speedometer#153]
I found this repository after taking a look at https://bugs.webkit.org/show_bug.cgi?id=220104.
```
%  report-non-inclusive-language --verbose
resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js.map: blacklist: 1
resources/todomvc/architecture-examples/vue/dist/js/chunk-vendors.fe2ee873.js.map: whitelist: 1
resources/tentative/editors/bigtext.js: slave: 1
resources/tentative/editors/dist/assets/index.es-8aa334e1.js: slave: 1
Total: 4 (blacklist: 1, whitelist: 1, slave: 2)
```
1. Can these resources be patched or do they also come from upstream somewhere?
2. Is it possible to patch earlier versions of Speedometer with regards to this issue?

**Comment by flashdesignory** [comment]
Hi @annevk - thank you for raising the issue.
We will take a look to see how we can resolve it. 

1. Let us do an audit to see what's the best way to address each case. 
2. Some workloads are new and don't need patching in previous versions of the app. Others are updated and we need to take a look if the same issue existed beforehand.

**Comment by rniwa** [comment]
This has gotten better but we still have one instance of blacklist and whitelist each:
```
Tools/Scripts/report-non-inclusive-language --verbose     
resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js.map: blacklist: 1
resources/todomvc/architecture-examples/vue/dist/js/chunk-vendors.fe2ee873.js.map: whitelist: 1
Total: 2 (blacklist: 1, whitelist: 1, slave: 0)
```

**Comment by rniwa** [comment]
Filed https://github.com/vuejs/core/issues/8416 for Vue.

**Comment by rniwa** [comment]
Hm... looks like React-Redux's usage of blacklist comes from https://github.com/mridgway/hoist-non-react-statics but the package has gotten rid of the non-inclusive language 3 years ago. It's just that React-Redux is using an old version of the package which still contains non-inclusive language. I wonder if we can force React-Redux example to use a newer version of https://github.com/mridgway/hoist-non-react-statics...

**Comment by flashdesignory** [comment]
@annevk - we just merged the last pr to remove non-inclusive language (https://github.com/WebKit/Speedometer/pull/286).

Are we good to close this issue?

**Comment by rniwa** [comment]
Still not quote gone:
```
% ../webkit/Tools/Scripts/report-non-inclusive-language --verbose
resources/todomvc/big-dom-generator/dist/app.bundle.js: whitelist: 1
resources/todomvc/big-dom-generator/dist/app.bundle.js: slave: 1
resources/todomvc/architecture-examples/vue-complex/dist/js/chunk-vendors.cbd90c7c.js.map: whitelist: 1
Total: 3 (blacklist: 0, whitelist: 2, slave: 1)
```

**Comment by rniwa** [comment]
We're good now. Thanks all for landing fixes.
```
% ../webkit/Tools/Scripts/report-non-inclusive-language 
Total: 0 (blacklist: 0, whitelist: 0, slave: 0)
```
