### ISSUE TITLE
Add a test picker UI to the main runner if ?developerMode is set

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#158]
Right now the only way to select tests in the UI is on the InteractiveRunner

**Comment by bgrins** [comment]
I'm imagining adding a `<dialog>` element when the param is set, and live updating the URL to the selected tests in that list

**Comment by rniwa** [comment]
MotionMark has developer.html page which allows you to configure things like this. Maybe we can use the same pattern here? Add developer.html which has a bunch of configuration UI. We can phase out InteractiveRunner.html at that point.

**Comment by bgrins** [comment]
I was thinking we'd have a test picker in both pages (always in interactive runner and conditionally in the main ui based on the developerMode param)

**Comment by bgrins** [comment]
Here's an example of what I'm thinking https://devmode-1--speedometer-preview.netlify.app/?developerMode. It will update the URL as you select tests and then it gets removed once the tests start (we could also consider expanding the UI over time to select iterationCount and other options).

**Comment by rniwa** [comment]
Yeah, that looks like a good UI. I'd like to see `cursor: hand` on the developer menu's toggle though.
