### ISSUE TITLE
Make some developerMode improvements

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#174]
A few improvements as follow up to #158 to help make configuring parameters easier for developers (without needing to remember the GET param names)

- [x] Add slider for iterationCount
- [x] useWarmupSuite checkbox
- [x] raf timer checkbox (once that lands)
- [x] Make ctrl/cmd+click on the `<label>` also toggle exclusively (right now it only does on the checkbox)
- [ ] Consider moving URL generation / encoding into the params object (https://github.com/WebKit/Speedometer/pull/188/files#discussion_r1205130775) 
- [x] Update the label for the iterationCount slider on `input` instead of `change`
- [x] Add UI for "tags" (#215)

**Comment by bgrins** [comment]
1-3 are added in #188

**Comment by bgrins** [comment]
2 more items covered by #194

**Comment by rniwa** [comment]
Do we need to keep this open? Are we planning to do this item?
> Consider moving URL generation / encoding into the params object

**Comment by bgrins** [comment]
The last remaining item is a minor code cleanup that I'm not likely to get to - if someone wanted to take it that'd be great but I'm also fine to just close out the issue
