### ISSUE TITLE
Consider a param for random test ordering

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#193]
Currently, if a GC happens to fall into a short-running test's measured time, it will hurt the overall score much more than if that GC falls in a long-running test's measured time, because of the geomean.

A developer param to toggle alternative ordering (including random ordering, optionally with a seed) would help us understand how much of an issue this is and if things like more closely aligning individual suite runtimes would be effective in making this less of an issue.

**Comment by rniwa** [comment]
This is an interesting idea. Pseudo random ordering of tests might be indeed useful to quantify the impact of GC and other timing sensitive work browsers do.

**Comment by bgrins** [comment]
@squarewave has been thinking more about this and other ways to help us understand and potentially mitigate issues caused by timing sensitive work that depends on the test order. Doug, do you prefer to discuss this in more detail in an upcoming call, or async in a doc?
