### ISSUE TITLE
Investigate CPU throttling effects

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#201]
We should measure the impact on various runner configurations on the final score on various platforms:

- Android (low-end and high-end devices)
- macOS (Apple Silicon and intel)
- linux (probably mostly intel desktop)
- windows (intel)

These are the axis we want to test:
- measurementMode: rAF vs. timer
- warmup Time:  0ms and 50ms
- step delay: 0ms, 50ms, 200ms

TODO:
- [x] Add params for step delay
- [x] Compile complete list of platforms we want to test
- [x] Compile list of test urls with parameters want to check

**Comment by camillobruni** [comment]
Once #202 lands we can use it directly until, I've hosted my branch:

Delayed steps without warmup, `delay in [0, 25, 50, 100, 200]`
- [default](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?startAutomatically)
- [25ms](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=25&startAutomatically)
- [50ms](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=50&startAutomatically)
- [100ms](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=100&startAutomatically)
- [200ms](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=200&startAutomatically)

Delayed steps with `warmup = 50ms` and `delay in [0, 25, 50, 100, 200]`

- [default + 50ms warmup](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?warmupBeforeSync=50&startAutomatically)
- [25ms + 50ms warmup](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=25&warmupBeforeSync=50&startAutomatically)
- [50ms + 50ms warmup](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=50&warmupBeforeSync=50&startAutomatically)
- [100ms + 50ms warmup](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=100&warmupBeforeSync=50&startAutomatically)
- [200ms + 50ms warmup](https://2023-05-31-delay-params--charming-squirrel-41ddae.netlify.app/?waitBeforeSync=200&warmupBeforeSync=50&startAutomatically)

**Comment by camillobruni** [comment]
MacBook Air M2 + Pixel 4 results (google sheets)[https://docs.google.com/spreadsheets/d/1-YHRAkuGEJTDo5ceYaDqAnAqkB5iLUZsSR6MAwB4_Oc/edit#gid=100920985]

<img width="753" alt="Screenshot 2023-06-06 at 16 39 30" src="https://github.com/WebKit/Speedometer/assets/129550/91022673-bdd4-41f2-a05c-c7727e666226">

<img width="753" alt="Screenshot 2023-06-06 at 16 39 44" src="https://github.com/WebKit/Speedometer/assets/129550/a93e9d30-2a03-40d8-ae4d-ccf5269f5a6e">

**Comment by MayuraRam** [comment]
Laptop- DELL Latitude 5540 (DC) with Intel i5-1350p (4P+8E [16 LC])(4.7GHz, 3.5GHZ) CPU
Browsers: Chrome 114.0.5735.134 & FireFox 114.0.1
Commit #c46e191e5207229b9f4daf1921cd30ffc20c390c was used. Removed Suite "TodoMVC-React-Complex-DOM" as it was failing intermittently with Safari on M2 MacOS.

Detailed data is available [here](https://docs.google.com/spreadsheets/d/1xGOhs54ga0JkY8CVFI53UUFSvJJSZiNwF7_SmRSbA0Y/edit?usp=sharing). 

![image](https://github.com/WebKit/Speedometer/assets/23691819/235ac2d7-e3aa-44e9-a0ee-5d31a8fd154b)

![image](https://github.com/WebKit/Speedometer/assets/23691819/fe46e5c5-4cb7-4f5a-b539-961f800f1edf)


<html>
<body>


Speedometer 3.0 Geomean (timeout based) |   |   |   |  
-- | -- | -- | -- | --
Delay | Chrome + no Warmup    | FireFox + no Warmup| Chrome + 50ms Warmup | FireFox + 50ms Warmup
0.0 ms | 1.00x | 1.00x | 0.88x | 1.12x
25.0 ms | 0.96x | 1.12x | 0.92x | 1.10x
50.0 ms | 1.16x | 1.28x | 1.00x | 1.11x
100.0 ms | 1.34x | 1.30x | 1.13x | 1.11x
200.0 ms | 1.39x | 1.31x | 1.15x | 1.11x
  |   |       |   |  
0.0 ms | 59.8 ms | 79.3 ms | 52.7 ms | 88.4 ms
25.0 ms | 57.6 ms | 88.8 ms   | 55.1 ms | 87.5 ms
50.0 ms | 69.5 ms | 101.2 ms   | 59.5 ms | 88.3 ms
100.0 ms | 80.0 ms | 103.1 ms   | 67.7 ms | 88.2 ms
200.0 ms | 83.1 ms | 104.1 ms    | 68.6 ms | 88.2 ms
  |   |   |   |  
  |   |   |   |  
  |   |   |   |  
  |   |   |   |  
Speedometer 3.0 Geomean (raf based) |   |   |   |  
Delay | Chrome+ no Warmup| FireFox + no Warmup | Chrome + 50ms Warmup | FireFox + 50ms Warmup
0.0 ms | 1.02x | 1.13x | 1.11x | 1.14x
25.0 ms | 1.08x | 1.26x | 1.09x | 1.10x
50.0 ms | 1.30x | 1.28x | 1.13x | 1.13x
100.0 ms | 1.38x | 1.33x | 1.14x | 1.21x
200.0 ms | 1.43x | 1.32x | 1.14x | 1.12x
  |   |   |   |  
0.0 ms | 60.8 ms | 89.6 ms   | 66.7 ms | 90.1 ms
25.0 ms | 64.9 ms | 100.2 ms   | 65.5 ms | 87.3 ms
50.0 ms | 77.7 ms | 101.2 ms   | 67.8 ms | 89.9 ms
100.0 ms | 82.8 ms | 105.6 ms   | 68.0 ms | 95.7 ms
200.0 ms | 85.8 ms | 105.0 ms   | 68.0 ms | 89.0 ms

</body>
</html>

**Comment by rniwa** [comment]
Hm... looks like there is ~10% discrepancy in Firefox when a delay of 25~50ms is added when there is no warmup.

**Comment by camillobruni** [comment]
Also there is quite a substantial different of the rAF vs timeout numbers on Firefox, while I didn't really see this on macOS.

**Comment by MayuraRam** [comment]
Three run data was collected on the DELL Latitude 5540 (DC) with Intel i5-1350p (4P+8E [16 LC])(4.7GHz, 3.5GHZ) CPU (DC mode) to verify the 1.13x seen with Firefox vs 1.02x seen with Chrome when using rAF vs Timer measurement methodologies. No significant difference between one run and three run data was seen.

Measurements were also collected on an Intel Desktop (i9 13900K) with Windows using Chrome and FireFox for the **default case only** to verify behavior seen by @Bas Schouten with i9 12900HK (See Slack channel)

The following table shows a summary. Detailed data is [here]. (https://docs.google.com/spreadsheets/d/1k9XK86b8gAStuF3y7lqBK8HvL_5eIrRCPF9397ttGNM/edit?usp=sharing).

<html>
<body>


Speedometer 3.0 Geomean (timeout based) (Lower duration [in ms] is better) |   |   |   |   |  
-- | -- | -- | -- | -- | --
  |   | Three run data | One run data |   | Three run data | One run data
  | i9_13900K (Desktop) | i5-1350p (Laptop) DC | i5-1350p (Laptop) DC | i5-1350p (Laptop) DC |   | i5-1350p (Laptop) DC | i5-1350p (Laptop) DC | i5-1350p (Laptop) DC
Delay | i9_13900K_Chrome + no warm up | i9_13900K_Firefox + no warm up | i5_1350p_FireFox + no warm up | i5_1350p_Chrome + no warm up | i5_1350p_FireFox + no warm up |   | i5_1350p_FireFox + 50 ms warm up | Chrome + 50ms Warmup | i5_1350p_FireFox + 50 ms warm up
0.0 ms | 1.00x | 1.00x | 1.00x | 1.00x | 1.00x |   | 1.11x | 0.88x | 1.11x
25.0 ms |   |   | 1.12x | 0.96x | 1.12x |   | 1.12x | 0.92x | 1.10x
50.0 ms |   |   | 1.26x | 1.16x | 1.28x |   | 1.14x | 1.00x | 1.11x
100.0 ms |   |   | 1.30x | 1.34x | 1.30x |   | 1.15x | 1.13x | 1.11x
200.0 ms |   |   | 1.33x | 1.39x | 1.31x |   | 1.12x | 1.15x | 1.11x
  |   |   |   |   |   |   |   |   |  
0.0 ms | 35.20 | 49.16 | 80.60 | 59.82 | 79.30 |   | 89.45 | 52.70 | 88.40
25.0 ms |   |   | 89.92 | 57.59 | 88.80 |   | 89.90 | 55.11 | 87.50
50.0 ms |   |   | 101.56 | 69.51 | 101.20 |   | 91.53 | 59.55 | 88.30
100.0 ms |   |   | 105.09 | 80.00 | 103.10 |   | 92.68 | 67.74 | 88.20
200.0 ms |   |   | 107.34 | 83.05 | 104.10 |   | 90.45 | 68.55 | 88.20
  |   |   |   |   |   |   |   |   |  
Speedometer 3.0 Geomean (raf based)  (Lower duration [in ms] is better) |   |   |   |   |  
Delay |   |   | i5_1350p_FireFox + no warm up | i5_1350p_Chrome + no warm up | i5_1350p_FireFox + no warm up |   | i5_1350p_FireFox + 50 ms warm up | Chrome + 50ms Warmup | i5_1350p_FireFox + 50 ms warm up
0.0 ms | 1.05x | 1.02x | 1.10x | 1.02x | 1.13x |   | 1.14x | 1.11x | 1.14x
25.0 ms |   |   | 1.12x | 1.08x | 1.26x |   | 1.11x | 1.09x | 1.10x
50.0 ms |   |   | 1.25x | 1.30x | 1.28x |   | 1.13x | 1.13x | 1.13x
100.0 ms |   |   | 1.33x | 1.38x | 1.33x |   | 1.12x | 1.14x | 1.21x
200.0 ms |   |   | 1.34x | 1.43x | 1.32x |   | 1.09x | 1.14x | 1.12x
  |   |   |   |   |   |   |   |   |  
0.0 ms | 37.07 | 50.17 | 88.45 | 60.80 | 89.60 |   | 91.70 | 66.68 | 90.10
25.0 ms |   |   | 90.62 | 64.87 | 100.20 |   | 89.78 | 65.48 | 87.30
50.0 ms |   |   | 101.05 | 77.66 | 101.20 |   | 91.37 | 67.83 | 89.90
100.0 ms |   |   | 107.42 | 82.81 | 105.60 |   | 90.20 | 67.97 | 95.70
200.0 ms |   |   | 107.88 | 85.82 | 105.00 |   | 88.24 | 68.00 | 89.00

</body>
</html>

**Some observations:**
There is a difference in behavior with Firefox on desktop and mobile systems with Intel CPUs and Windows OS with the default test case – No Warmup, No delay when comparing Timer vs rAF measurement methodologies. 

- On desktop, for the default case of Timer vs rAF with no delay and no warm up, Chrome and Firefox rAF relative time performance is comparable (1.05x and 1.02x respectively)
- On a laptop rAF vs Timer is 1.02x to 1.07x on Chrome and ~1.10x on Firefox with no delay, with or without warmup. 
- On a laptop, of the 17 workloads the following 4 have ratios above 1.10x for relative time with rAF vs Timer.  TodoMVC-Svelte is the most impacted.

<html>
<body>


  | no warm up, no delay | 50 ms warm up, no delay
-- | -- | --
TodoMVC-Preact | 1.34x | 1.53x
TodoMVC-Svelte | 1.54x | 1.95x
NewsSite-Next | 1.13x | 1.12x
Charts-observable-plot | 1.44x | 1.43x


</body>
</html>

See detailed info in this [sheet](https://docs.google.com/spreadsheets/d/1k9XK86b8gAStuF3y7lqBK8HvL_5eIrRCPF9397ttGNM/edit?usp=sharing) -  workload component steps with ratios above 1.10x are highlighted in green in the tab "RAF comparison”. Tab "RAF comparison" columns K through R shows similar comparison with M2 Firefox (From Camillo’s data)

**Comment by rniwa** [comment]
Now that we've established 25ms delay introduces a degradation in the score when using rAF, it would be useful to observe what happens with 5ms, 10ms, 15ms, and 20ms delays. If we see no difference between 0ms and 15ms, then we're probably good to go because it means any delay of up to 15ms is of little to no consequence since rAF method will only introduce at most 15ms difference (assuming the step itself takes at least 1ms to run).

**Comment by rniwa** [comment]
Now that we've switched to rAF based approach, can we call this done? Is there anything left to do?
