### ISSUE TITLE
Consider using nanoid's non-secure version of id generation

### ISSUE THREAD

**Issue by julienw** [WebKit/Speedometer#204]
I noticed that [nanoid is used inside redux toolkit's `createAsyncThunk`](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/nanoid.ts), so I had a look at its usage, and it looks like [nanoid](https://github.com/ai/nanoid) is used a lot (28M downloads on npm, ported to other languages as well). It would make sense to include this as our id generator in at least one of our workload:

https://github.com/ai/nanoid/blob/950dbdaefef465cc6925c6ec596b3478233a1c2d/non-secure/index.js#L23-L32

Here is our current version that I believe we use in a lot of places: https://github.com/WebKit/Speedometer/blob/e1957e39199e0a6ee361ddd1e61a95b485460394/resources/todomvc/architecture-examples/react/src/todo/reducer.js#L1-L16

What do you think @flashdesignory ?

**Comment by flashdesignory** [comment]
@julienw - nice, totally open to change a workload to use nanoid. 
Did you have a specific workload in mind? React or React-Redux TodoMVC app?

**Comment by julienw** [comment]
We could pick one short-running (preact or svelte), one "normal" running (React, Angular) and possibly one long-running (jQuery)?

**Comment by flashdesignory** [comment]
Let's do Preact and React, if no-one has different opinions. 
Svelte already uses a different version that I'd like to keep.
