### ISSUE TITLE
Next, Nuxt and CodeMirror suites seem to use requestIdleCallback

### ISSUE THREAD

**Issue by rniwa** [WebKit/Speedometer#240]
It looks like Nuxt and CoreMirror have code pertaining to `requestIdleCallback`. We should probably manually undefined the method on window for consistency since Safari / WebKit doesn't implement this feature.

**Comment by rniwa** [comment]
Next seems to use requestIdleCallback as well.

**Comment by julienw** [comment]
I couldn't find where this was discussed.
Maybe the ship has sailed now, but I'd like to at least raise the argument that if the lack of `requestIdleCallback` impairs Safari, this may be a good enough reason for Safari to implement it. (I know that's not easy given the current state of things).

**Comment by rniwa** [comment]
> I couldn't find where this was discussed. Maybe the ship has sailed now, but I'd like to at least raise the argument that if the lack of `requestIdleCallback` impairs Safari, this may be a good enough reason for Safari to implement it. (I know that's not easy given the current state of things).

I don't think the presence of requestIdleCallback changes Safari's score one or another based on the measurements I've made on Chrome & Firefox. This change was purely based on the desire to run the same code in all browser engines.
