### ISSUE TITLE
class Metric extends LabeledObject does [A-z] instead of [A-Z]

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#280]
the [Metric](https://github.com/WebKit/Speedometer/blob/91f54a9c6d906a3e4b7ffe34a2be3026e84aadc2/resources/perf.webkit.org/public/v3/models/metric.js#L12) class uses a wrong regexp character range: `[A-z]` instead of `[A-Z]`

**Comment by rniwa** [comment]
Fixed by https://github.com/WebKit/Speedometer/commit/d834dcbb079c5251b823a8539957b65b8be6395e
