### ISSUE TITLE
`benchmark-report.js` is broken

### ISSUE THREAD

**Issue by squarewave** [WebKit/Speedometer#30]
We're looking to get a head start on setting this up in CI, and historically we've used `benchmark-report.js` to drive the execution. However it's broken now because we pulled all of the global functions like `startBenchmark` to be part of `main.js`'s MainBenchmarkClient. Is the plan to add a base class to this that `benchmark-report.(m)js` can subclass and call `startBenchmark` on? It would be nice if we could nail down a plan for this in the near term so that our devs working on CI can get something stood up.

EDIT: I had `benchmark-runner.js` confused with `benchmark-report.js` - fixed now.

**Comment by housseindjirdeh** [comment]
@squarewave Are you planning to set up a unit or integration testing pipeline in CI? I was about to start going down that path, but don't want to duplicate efforts.

**Comment by squarewave** [comment]
We were just planning to get a head start on setting up benchmarking of Firefox in Mozilla's CI. Historically we've used what `benchmark-runner.js` sets up to make extracting scores easier for us.

**Comment by squarewave** [comment]
Woops! I've been typoing the name in this issue. I am actually referring to `benchmark-report.js`.

**Comment by camillobruni** [comment]
Is this still broken for you?

**Comment by rniwa** [comment]
This appears to be functional now. Please comment if it's still broken.
