### ISSUE TITLE
Additional task is scheduled in the async time of NewsSite-Next case

### ISSUE THREAD

**Issue by shiyu-zhang** [WebKit/Speedometer#302]
RAF measurement method is intended to include the complete render reflow process in the async time. However, current RAF measurement method will also result in additional async task is scheduled in the async time of the NewsSite-Next case. It's because _syncCallback and _asyncCallback timer are registered in separate RAFs. The Timer measurement method does not have this problem as it registers _syncCallback and _asyncCallback timer in the same setTimeout. Is it on purpose to include such async task in the async time?

![image](https://github.com/WebKit/Speedometer/assets/28973499/1b122fff-fe23-4603-8712-566839c5b723)

A quick hack to verify the score impact:
![image](https://github.com/WebKit/Speedometer/assets/28973499/f3ef647c-ab50-4a04-b8c8-7ab43ecd2b61)

**Comment by rniwa** [comment]
Yes, we've specifically designed rAF based measurement to include all async operations in async time including cases like this.

**Comment by shiyu-zhang** [comment]
Thanks, glad to know that.
