### ISSUE TITLE
Speedometer repository cannot be cloned cleanly in a case insensitive filesystem

### ISSUE THREAD

**Issue by rniwa** [WebKit/Speedometer#304]
https://github.com/WebKit/Speedometer/pull/301 broke the Speedometer repository under a case insensitive filesystem. We have lowercase readme.md & uppercase README.md in resources/todomvc/architecture-examples/react-complex/ and this causes git clone to fail in a case insensitive filesystem.

**Comment by bgrins** [comment]
This is fixed now, right?

**Comment by rniwa** [comment]
Yup.
