### ISSUE TITLE
TodoItem component in TodoMVC-WebComponents uses "title" and "id" property names which conflict with built-in properties

### ISSUE THREAD

**Issue by mstange** [WebKit/Speedometer#313]
I think the TodoItem component in [todo-item.component.js](https://github.com/WebKit/Speedometer/blob/8fd080fb6706bdc7a94956720655795f4536dbbf/resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-item/todo-item.component.js) may be setting attributes in unintended ways because it uses the property names "id" and "title".

As far as I can tell, this doesn't have any bad consequences or performance impact, but it seems unintended. I think it should either be fixed in some way, or comments should be added to call out this behavior.

Details:

TodoItem extends HTMLElement. Elements have existing setters for the properties "id" and "title". When the component assigns to `this.id` or `this.title`, this causes the browser's implementation of the existing setters to run, which convert these property sets into internal `setAttribute` calls. This can have surprising consequences.

For example, take this line in the `TodoItem` constructor: https://github.com/WebKit/Speedometer/blob/8fd080fb6706bdc7a94956720655795f4536dbbf/resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-item/todo-item.component.js#L17

We set this.title to "Todo Item". This causes the browser to set the `title` attribute to `Todo Item`. This causes `attributeChangedCallback` to run with `property = "title"`, `oldValue = null` and `newValue = "Todo Item"`:

https://github.com/WebKit/Speedometer/blob/8fd080fb6706bdc7a94956720655795f4536dbbf/resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-item/todo-item.component.js#L146-L153

We hit the line `this[property] = newValue;`, which sets `this.title` to "Todo Item" again. This causes `attributeChangedCallback` to run again, inside itself, this time with `oldValue = "Todo Item"` and `newValue = "Todo Item"`. Then we take the early exit.

So the constructor is causing re-entrant calls to `attributeChangedCallback`. Furthermore, the constructor is setting attributes, which does not comply with the rules under [4.13.2 Requirements for custom element constructors and reactions](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

> The element must not gain any attributes or children, as this violates the expectations of consumers who use the [createElement](https://dom.spec.whatwg.org/#dom-document-createelement) or [createElementNS](https://dom.spec.whatwg.org/#dom-document-createelementns) methods.

**Comment by flashdesignory** [comment]
Thanks for raising the issue and for the detailed explanation @mstange!
If I understand the concern correctly, using different names for "id" and "title" would resolve the issue?
We could simply rename "id" to "itemId" and "title" to "itemTitle", since that wouldn't clash with existing attributes.

**Comment by mstange** [comment]
I think that would address it, yes.

I wonder if there are other conventions for authoring custom elements we could follow when it comes to reflecting attribute values to internal properties. I haven't written JS code which uses custom elements myself, so I'm not sure if this is a common issue that people know how to work around.

**Comment by flashdesignory** [comment]
Awesome - I'll make the change in the pr and link to this issue. 

I assume most people probably don't think about the consequences, similar to what happened here. 
It's good to have an example though that showcases best practices. 
I'll add a comment as well, explaining why we renamed the properties.

**Comment by mstange** [comment]
Fixed by #314.
