### ISSUE TITLE
Potentially unused branches

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#320]
Seems like there are a couple of branches in this main repo that either look like experiments or stale.
<img width="254" alt="Screenshot 2023-10-03 at 10 17 51" src="https://github.com/WebKit/Speedometer/assets/129550/d1db1a3a-347f-42eb-aa71-0e98fda3e561">

Would it make sense to clean those up and only have dedicated branches?
- `main` => current development branch
- `experimental` => main + future / experimental workloads
- `v2.1` => what is currently `speedometer2.1-content`
- `v3.0` => "stable" / released version 3, once we're there

**Comment by bgrins** [comment]
Makes sense to me

**Comment by rniwa** [comment]
> `v2.1` => what is currently `speedometer2.1-content`

This isn't quite right. This branch isn't pure 2.1 but rather 2.1 benchmark content adopted to 3's test runner so it's hybrid of the two.

**Comment by bgrins** [comment]
> This isn't quite right. This branch isn't pure 2.1 but rather 2.1 benchmark content adopted to 3's test runner so it's hybrid of the two.

Good call, that should stay as-is

**Comment by bgrins** [comment]
I think we can close this after discussing in last week's meeting. We're agreed on the proposal in @camillobruni's comment, with the clarification for experimental not being "future". @rniwa deleted the unused branches so we now have `main` and `speedometer2.1-content`. Once we have content for it we can push it into the `experimental` branch.
