### ISSUE TITLE
benchmark on power efficiency of background tabs is missing

### ISSUE THREAD

**Issue by DarkoVeberic** [WebKit/Speedometer#33]
while everybody seems to be focused on making browsers faster for foreground pages the cpu-power and memory demands of background tabs have lately visibly exploded. in the past having many tabs open did not really cost much but nowadays certain systems can be completely crippled by such work habits. in the speedometer testsuite an "anti-speed" metrics for background tabs is missing. in contrast to the foreground tab, the background tabs should consume an amount of resources as small as possible and i am sure this can and should be measured somehow in your new project.

btw, tanks for your efforts to speed-up the web! nevertheless, let us think also about the unnecessary energy resources every day consumed by the billions of unused tabs!

**Comment by rniwa** [comment]
I'm pretty certain this is outside the scope of Speedometer 3 effort. There might be a desire to create a cross-browser power benchmark but workload for such a benchmark will be vastly different from Speedometer 3 content.

**Comment by rniwa** [comment]
Closing this as out-of-scope.
