### ISSUE TITLE
Enable cross origin isolated headers on  browserbench.org

### ISSUE THREAD

**Issue by rniwa** [WebKit/Speedometer#334]
We should consider enabling cross origin isolated in browserbench.org so that `performance.now` will be high precision. See https://web.dev/articles/coop-coep for details.

**Comment by rniwa** [comment]
At this point, I don't think we're doing this for v3. Perhaps v3.1?

**Comment by julienw** [comment]
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

**Comment by rniwa** [comment]
## Chrome
### Before
28.8 ± 1.5
28.6 ± 0.74
29.4 ± 0.70

### After
28.8 ± 1.8
29.2 ± 0.70
28.8 ± 0.82


## Firefox
### Before
29.7 ± 1.8
29.0 ± 0.99
29.6 ± 0.84

### After
29.4 ± 1.7
28.5 ± 0.91
29.8 ± 1.0


## Safari
### Before
30.9 ± 1.3
31.0 ± 1.4
30.9 ± 1.1

### After
30.7 ± 1.9
31.6 ± 1.2
31.2 ± 1.2

[COOP-COEP-results.zip](https://github.com/WebKit/Speedometer/files/14858969/COOP-COEP-results.zip)

**Comment by rniwa** [comment]
# MotionMark results

## Chrome

### Before
5883.73 @ 60fps ±3.31%
5976.08 @ 60fps ±5.32%
5844.08 @ 60fps ±3.34%

### After
5821.87 @ 60fps ±5.49
5981.02 @ 60fps ±5.12%
5876.91 @ 60fps ±3.63%


## Firefox

### Before
1890.53 @ 60fps ±9.10%
1942.99 @ 60fps ±2.42%
1923.33 @ 60fps ±2.21%

### After
1927.66 @ 60fps ±2.15%
1945.62 @ 60fps ±6.45%
1922.74 @ 60fps ±4.08%


## Safari

### Before
5759.77 @ 60fps ±1.21%
5859.96 @ 60fps ±4.39%
5871.36 @ 60fps ±5.60%

### After
5827.52 @ 60fps ±2.68%
5843.08 @ 60fps ±10.12%
5852.35 @ 60fps ±6.61%

**Comment by rniwa** [comment]
Done this.
