### ISSUE TITLE
List of Existing Browser Benchmarks (informative)

### ISSUE THREAD

**Issue by vprelovac** [WebKit/Speedometer#34]
Greetings!

I am welcoming the joint-benchmark effort in front of the [Orion browser](https://browser.kagi.com) team.

Dumping here my collection of known and less known browser benchmarks in case it sparks inspiration for features to be included by the comitee.

http://html5test.com
https://www.wirple.com/bmark/
https://www.antutu.com/html5/
http://www.speed-battle.com/speedtest_e.php
https://web.basemark.com/
https://mozilla.github.io/krakenbenchmark.mozilla.org/
https://www.principledtechnologies.com/benchmarkxprt/webxprt/
http://perftest.dynamis.jp/stylebench/
https://testdrive-archive.azurewebsites.net/performance/mazesolver/default.html
https://takahirox.github.io/WebAssembly-benchmark/
https://www.kevs3d.co.uk/dev/canvasmark/
https://pspdfkit.com/webassembly-benchmark/
https://testdrive-archive.azurewebsites.net/performance/chalkboard/
https://openbenchmarking.org/suite/pts/browsers
https://luic.github.io/WebGL-Performance-Benchmark/

**Comment by rniwa** [comment]
Closing this since there is no action to take here beyond observing the existence of these benchmarks.
