### ISSUE TITLE
Link the latest hosted speedometer version from older versions

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#345]
It would be nice to make sure that older versions of Speedometer point to `https://browserbench.org/Speedometer/` which should host the latest version.
This would make it a bit more obvious for folks that accidentally end up on older versions via search engines.

**Comment by bgrins** [comment]
https://github.com/WebKit/WebKit/pull/24924

**Comment by rniwa** [comment]
Completed as https://commits.webkit.org/275760@main.
