### ISSUE TITLE
Idea: Rendering performance test by loading large .json

### ISSUE THREAD

**Issue by vprelovac** [WebKit/Speedometer#35]
All rendering engines struggle with rendering a simple large .json file

https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json

This takes about 30 seconds to render completely on my machine in WebKit/Gecko/Blink. It should take 1-2 seconds.

**Comment by rniwa** [comment]
We're not trying to create a page loading benchmark.

**Comment by vprelovac** [comment]
This is not a page load benchmark but a DOM creation and traversal benchmark. The data would be pre-loaded (cached) for the purpose of the test.
