### ISSUE TITLE
Add general run instructions

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#352]
Let's collect some general (and browser specific) instructions to get consistent Speedometer 3 scores across browsers and platforms.

WIP [google document](https://docs.google.com/document/d/1J4TXULBtnbBLtYYkwlrbK1RWgBWl-M5jTTA_n2gbkkY/edit?tab=t.0#heading=h.5aqetjfqhr8s) to collect information.

**Comment by bgrins** [comment]
Based on the discussion today here, the likely outcome is 

1) Some text to replace the current text on the homepage (`Speedometer is a browser benchmark that measures the responsiveness of Web applications. It uses demo web applications to simulate user actions such as adding to-do items.`)
2) A more detailed runbook for people who want to report the most accurate scores

**Comment by rniwa** [comment]
Yeah, I guess it would be good to point out things like clearing the cache, disabling all browser extensions, etc... for the detailed instructions.
