### ISSUE TITLE
Idea: Popular page rendering performance

### ISSUE THREAD

**Issue by vprelovac** [WebKit/Speedometer#36]
Most browser benchmarks are synthetic in nature.

The idea is to augment such tests with rendering of pre-saved (WARC format?) popular pages from the web. For example a combination of news articles, amazon product page, youtube video etc. 

Benchmark would consist of rendering these pages end to end, when loaded from cache.

**Comment by rniwa** [comment]
We're not trying to create a page loading benchmark.
