### ISSUE TITLE
eliminate flickering/flashing while test is running

### ISSUE THREAD

**Issue by willfs84** [WebKit/Speedometer#37]
There is a flickering/flashing while running Speedometer. It's unpleasant even for people that do not have photosensitive epilepsy and similar issues. There has to be a way to avoid this flashing/flickering (perhaps simply making everything dark mode?)

**Comment by willfs84** [comment]
It's the high contrast flashing/flickering that's the big problem (white flashing against a black background or vice versa). If they decide to make everything white or everything dark it should pretty much eliminate this

**Comment by bgrins** [comment]
There's probably more we can do over time, but I'm going to close this out after https://github.com/WebKit/Speedometer/pull/151 (making the running iframe always have a light background)
