### ISSUE TITLE
Make clear that Speedometer v3 is a cross-browser effort on browserbench.org

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#379]

**Comment by camillobruni** [comment]
Some quick hacky attempt:
<img width="1404" alt="Screenshot 2024-02-21 at 22 50 23" src="https://github.com/WebKit/Speedometer/assets/129550/0ebe89e1-91f2-48ef-9c8f-463f5452cd0c">

**Comment by jrmuizel** [comment]
From the screenshot it's not clear to me that the "Jointly maintained..." only applies to Speedometer. Moving into the description text would make this clearer.

**Comment by jrmuizel** [comment]
Yeah, that's clearer.

**Comment by rniwa** [comment]
I'm gonna revise the description to "It's maintained by major browser engine developers under an open governance model" since it's not like there are grand total of three developers lol.

**Comment by bgrins** [comment]
https://github.com/WebKit/WebKit/pull/24924

**Comment by rniwa** [comment]
Completed as https://commits.webkit.org/275760@main.
