### ISSUE TITLE
The set of TodoMVC workloads listed in about.html needs to be updated.

### ISSUE THREAD

**Issue by sulekhark** [WebKit/Speedometer#380]
The text does not reflect the currently enabled workloads:

![image](https://github.com/WebKit/Speedometer/assets/16363629/89b6b3ff-3c65-41b1-90bf-376f113f6b15)

**Comment by rniwa** [comment]
What are the differences?

**Comment by sulekhark** [comment]
The current enabled workloads are (the different lines are bolded):

<a href="resources/todomvc/vanilla-examples/javascript-es5/readme.md" target="_blank">TodoMVC-JavaScript-ES5</a>,
**<a href="resources/todomvc/vanilla-examples/javascript-es6-webpack-complex/readme.md" target="_blank">TodoMVC-JavaScript-ES6-Webpack-Complex-DOM</a>**,
<a href="resources/todomvc/vanilla-examples/javascript-web-components/readme.md" target="_blank">TodoMVC-WebComponents</a>,
<a href="resources/todomvc/architecture-examples/react-complex/readme.md" target="_blank">TodoMVC-React-Complex-DOM</a>,
**<a href="resources/todomvc/architecture-examples/react-redux/readme.md" target="_blank">TodoMVC-React-Redux</a>**, 
<a href="resources/todomvc/architecture-examples/backbone/readme.md" target="_blank">TodoMVC-Backbone</a>, 
**<a href="resources/todomvc/architecture-examples/angular-complex/readme.md" target="_blank">TodoMVC-Angular-Complex-DOM</a>**,
<a href="resources/todomvc/architecture-examples/vue/readme.md" target="_blank">TodoMVC-Vue</a>,
<a href="resources/todomvc/architecture-examples/jquery/readme.md" target="_blank">TodoMVC-jQuery</a>,
**<a href="resources/todomvc/architecture-examples/preact-complex/readme.md" target="_blank">TodoMVC-Preact-Complex-DOM</a>**,
**<a href="resources/todomvc/architecture-examples/svelte-complex/readme.md" target="_blank">TodoMVC-Svelte-Complex-DOM</a>**,
**<a href="resources/todomvc/architecture-examples/lit-complex/readme.md" target="_blank">TodoMVC-Lit-Complex-DOM</a>**
