### ISSUE TITLE
InteractiveRunner.html doesn't load (ever since the conversion to ES6 modules)

### ISSUE THREAD

**Issue by dholbert** [WebKit/Speedometer#39]
Steps to reproduce:
(1) `git clone https://github.com/WebKit/Speedometer && cd Speedometer && python -m http.server 8123`
(2) Visit `http://localhost:8123/InteractiveRunner.html` in a browser

ACTUAL RESULTS:
The page doesn't load. It has failed `GET` requests for these URLS (whose corresponding files actually now have .mjs as their suffix):
```
  http://localhost:8123/resources/benchmark-runner.js
  http://localhost:8123/resources/tests.js
```
and then it throws an `Uncaught ReferenceError: BenchmarkRunner is not defined` in `startTest`.

This issue started with this commit:
https://github.com/WebKit/Speedometer/commit/878783333437834177e3c3483b1e2029a11b030c

If you checkout the [parent](https://github.com/WebKit/Speedometer/commit/1e6af3de5f7aa3db47e059369a06da874347e344) of that commit, then InteractiveRunner.html is a usable interactive test selector page.

**Comment by dholbert** [comment]
(Note: I am not an expert in JS, and know very little about JS modules. The following is me shooting in the dark, and hopefully it's helpful for someone else to address this fully.)

I found two trivial fixes that are needed right off the bat, to these lines of InteractiveRunner.html:
```
<script src="resources/benchmark-runner.js" defer></script>
<script src="resources/tests.js" defer></script>
```
https://github.com/WebKit/Speedometer/blob/dce4dfeaa060e89530f1e563c2735ab97653cf31/InteractiveRunner.html#L5-L6

(1) `s/js/mjs/` (correct the filename)
(2) We also need to add `type="module"` to each of those^ `<script>` tags, or else you get errors like `Uncaught SyntaxError: Unexpected token export`.

With those fixed (the filename and the type), the page still fails to load; it still throws the same ReferenceError that I quoted in the initial comment here about `BenchmarkRunner` not being defined (even though it's defined in `benchmark-runner.mjs`).  Presumably there's some other bit of visibility/importing boilerplate that's required to have access to that name...

(Hoping someone else can pick this up from here and make what is probably a trivial fix to get this working. Possibly @camillobruni who did the ES6-module-conversion here?)

**Comment by juliandescottes** [comment]
For info there's an ongoing PR to fix the interactive runner at #31, which should also fix this issue. I assume it should land soon.

**Comment by dholbert** [comment]
Aha, thanks!

**Comment by bgrins** [comment]
Hopefully this if fixed with 31 landing. @dholbert please shout if you're still seeing problems.

**Comment by dholbert** [comment]
Yup, this seems fixed now. Thanks!
