### ISSUE TITLE
With privacy.resistFingerprinting set to true in Firefox, Speedometer shows the result Infinity

### ISSUE THREAD

**Issue by julienw** [WebKit/Speedometer#399]
This was reported by some people on social networks. We found that setting privacy.resistFingerprinting to true was triggering this. But this might happen in some other cases too.

When doing it, some subtests take 0ms on every run, this may mess up the results.
Any chance we can fix this?

**Comment by bgrins** [comment]
I could imagine a warmup step where it looks for anomalies and shows a warning, like MotionMark does with refresh rate, but this case is likely rare in practice so a guardrail on the score display may be sufficient.

**Comment by julienw** [comment]
But I don't understand why one single substep being at 0 would yield an Infinity result. I'm not great at statistics, but I smell something fishy here.

**Comment by julienw** [comment]
> But I don't understand why one single substep being at 0 would yield an Infinity result.

actually this makes sense.
The geomean is a product, so a single substep to 0 poisons the geomean for this run.
Then a score is `1000 / geomean`, so we get `Infinity` for this run.
Then we geomean the scores from each iteration, and of course when do the product of `Infinity` with anything else we get `Infinity` too.

[The wikipedia page for geomean](https://en.wikipedia.org/wiki/Geometric_mean) says:
> The geometric mean can be an unreliable measure of central tendency for a dataset where one or more values are extremely close to zero in comparison to the other members of the dataset. 

Therefore I wonder if the use of geomean is appropriate.
Geomeaning the scores between runs, or the tests between runs, makes sense. But geomeaning the various tests together, I'm not so sure. I guess this ship has sailed for v3 though, so a quick fix might be to replace 0 by 1 when adding values in https://github.com/WebKit/Speedometer/blob/bd9ab77462618ce857c1e0aaf890936de18a33ad/resources/metric.mjs#L65-L69 ?

What do you think @camillobruni ?

**Comment by julienw** [comment]
Note: I also noticed errors with NaN values in the SVG rendering of the Details view, I believe this comes from the same issue.

**Comment by julienw** [comment]
I find our score computation very difficult to follow, where we do the same thing in different ways in different files: benchmark-runner.mjs vs metric.mjs vs Statistics.mjs, with no clear comment about the formula we use to calculate the score. It's very unclear to understand where the geomean that we use as the basis for the score is computed from.

**Comment by julienw** [comment]
Yeah indeed, 0 is an absurd number in this case. Is it practical to ignore the test instead of failing generally ?

**Comment by rniwa** [comment]
The point of using geometric mean across suites is to give each suite the same weight. If we used arithmetic mean, we would give more weights to the long running / slow suites.
