### ISSUE TITLE
Run the unit test from #40 in CI

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#43]
We discussed running the tests from #40 in a github action in browsers. I put together some minimal boilerplate to run selenium across Chrome, Firefox and Safari in a github action on macos in https://github.com/bgrins/crossbrowser-selenium-action-test.  Here's the job: https://github.com/bgrins/crossbrowser-selenium-action-test/blob/main/.github/workflows/blank.yml and here's the test using it: https://github.com/bgrins/crossbrowser-selenium-action-test/blob/main/test.js.

I imagine what we'd do is take something like that, but instead of loading example.com we'd start a web server and load the test file in the browser - then wait for a success message or something in the tab. What do you think @housseindjirdeh?

**Comment by bgrins** [comment]
There's surely a better way to do some of the plumbing here, but I prototyped action integration on top of your unit test PR, which looks like: https://github.com/housseindjirdeh/Speedometer/compare/benchmark-runner-tests-mocha...bgrins:Speedometer:mocha-in-ci?expand=1.

Basically it's setting the mocha run result on the window global (https://github.com/bgrins/Speedometer/blob/b8cd728741bc837cef1a2c9d59ce7ce8eed8b64d/tests/index.html#L34) and waiting for that to complete then reading the reported state and asserting that it has > 0 passes and 0 failures. (https://github.com/bgrins/Speedometer/blob/b8cd728741bc837cef1a2c9d59ce7ce8eed8b64d/tests/unit-test-run.js#L82).

Confirmed a failure gets reported at https://github.com/bgrins/Speedometer/actions/runs/4011138042 and passing at https://github.com/bgrins/Speedometer/actions/runs/4011143543

**Comment by housseindjirdeh** [comment]
> I imagine what we'd do is take something like that, but instead of loading example.com we'd start a web server and load the test file in the browser - then wait for a success message or something in the tab. What do you think @housseindjirdeh?

I was thinking along the same lines. Overall your approach sounds good to me, as long as failures and successes get reported correctly for each browser than I think we're off to a great start (and your examples seem to show that). If you open a PR I can try running your actions locally.

**Comment by bgrins** [comment]
alright, green Action run in https://github.com/WebKit/Speedometer/actions/runs/4019867153! Closing via https://github.com/WebKit/Speedometer/pull/45
