### ISSUE TITLE
Safari is slow when running TodoMVC-React-Complex-DOM

### ISSUE THREAD

**Issue by camillobruni** [WebKit/Speedometer#434]
We're observing some odd slow runs with Safari when running  TodoMVC-React-Complex-DOM:

Just TodoMVC-React-Complex-DOM [url](https://speedometer-main.netlify.app/?developerMode=&iterationCount=5&suites=TodoMVC-React-Complex-DOM#details):
![Screenshot 2024-10-10 at 15 21 49](https://github.com/user-attachments/assets/486414db-aba6-4d4f-9b70-76de6b29a5f7)

Two workloads [url](https://speedometer-main.netlify.app/?developerMode=&iterationCount=5&suites=TodoMVC-React,TodoMVC-React-Complex-DOM#details):
![Screenshot 2024-10-10 at 15 21 40](https://github.com/user-attachments/assets/235c7aef-5496-4b3a-a810-3b80918f50cc)

All workloads [url](https://speedometer-main.netlify.app/?developerMode=&iterationCount=5#details): 
![Screenshot 2024-10-10 at 15 21 26](https://github.com/user-attachments/assets/43d255a3-77af-4e92-93f7-c46236d116a7)

We've noticed that Safari displays some additional faint content for a few frames when running slowly:
<img width="795" alt="Screenshot 2024-10-10 at 15 16 20" src="https://github.com/user-attachments/assets/aedddcde-c910-46ae-bb78-65cd588bedad">
We haven't observed this in Firefox or Chrome on macOS.

**Comment by rniwa** [comment]
Is this with Speedometer 3? Or with the latest main of Speedometer repository?

**Comment by camillobruni** [comment]
So far I  can only reliably reproduce it with the local `npm run dev` server.

**Comment by rniwa** [comment]
Thanks for reporting the issue. We've identified the root cause and will be fixing it in WebKit.
