### ISSUE TITLE
Interactive runner doesn't allow specifying the number of iterations

### ISSUE THREAD

**Issue by jrmuizel** [WebKit/Speedometer#46]
It seems like there's some support for this if you manually specify it in the URL with `iterationCount` but it doesn't work for me.

**Comment by bgrins** [comment]
I think this is a type error:

```
var searchParams = new URLSearchParams(window.location.search); 
searchParams.get('iterationCount')
> "1" 
```

Which leads to an error at https://github.com/WebKit/Speedometer/blob/adc3cca86091bb04a3fd97858fc11b54e7a74421/resources/interactive.mjs#L14:
```
Uncaught Error: iterationCount must be a positive integer.
    InteractiveBenchmarkRunner interactive.mjs:15
    startTest interactive.mjs:233
```
