### ISSUE TITLE
Add auto-formatting

### ISSUE THREAD

**Issue by flashdesignory** [WebKit/Speedometer#56]
Currently, the app does not enforce a code style and therefore does not have any automated steps to safeguard against deviations of styles when contributing to the codebase. 

A safe assumption is to use the [Webkit Code Style Guidelines](https://webkit.org/code-style-guidelines/) as a base and compare against some current webkit implementations, for example [this](https://github.com/WebKit/WebKit/blob/main/Source/WebInspectorUI/.eslintrc). 

Tools like eslint, prettier (and even stylelint) can help to enforce a consistent agreeable coding standard and lets us set up an automated flow to consistently run these tools automatically, before pushing any changes to Github.

**Comment by bgrins** [comment]
Resolved by https://github.com/WebKit/Speedometer/pull/57
