### ISSUE TITLE
Improve the reporting of multiple runs with the interactive runner

### ISSUE THREAD

**Issue by jrmuizel** [WebKit/Speedometer#59]
It seems like the scores across runs are not aggregated or summarized in any way. It would be nice if they were.

**Comment by bgrins** [comment]
https://github.com/WebKit/Speedometer/pull/42 might fix this (in the main runner). Longer term AIUI the plan is to have the main runner evolve any necessary interactive functions like stepping behind some kind of developer UI (query string, etc).

**Comment by bgrins** [comment]
Closing this one due to #42 and related work. The Details view has a rich UI for aggregation now. I believe @camillobruni has talked about a standalone analysis page and some other smaller improvements but I think any follow ups can be handled separately from this issue.
