### ISSUE TITLE
The UI gets shifted out of view on page load

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#96]
STR:
* `npm run dev`
* Open http://localhost:7000/

Then it navigates client side to http://localhost:7000/#home and looks like this (not fully visible until I scroll back up)

<img width="926" alt="Screenshot 2023-03-10 at 1 27 26 PM" src="https://user-images.githubusercontent.com/95570/224431632-d057a21b-5b24-412b-9549-37f3781cb0d9.png">

@camillobruni maybe this is related to the hash navigation changes?

**Comment by camillobruni** [comment]
I can't repro this anymore on current HEAD.
Which original window size did you use?

**Comment by bgrins** [comment]
Huh - I don't see this anymore either. Let's close this out and I'll reopen if I see it again.
