### ISSUE TITLE
Change the panning and zooming behavior for React-Stockcharts tests

### ISSUE THREAD

**Issue by bgrins** [WebKit/Speedometer#97]
As @squarewave mentioned in https://github.com/WebKit/Speedometer/pull/11#issuecomment-1366851864, it's unrealistic to send i.e. 50 wheel events to paint 50 frames inside of a single request animation frame callback (https://github.com/WebKit/Speedometer/blob/f16557016d2a0bd8f512611c34cc6538afdde121/resources/tests.mjs#L385).

We could consider breaking them up into a handful of steps where we one or a few events. I'm not sure if this would then cause issues on fast desktop hardware where the steps become too short to be effectively measured, but we should take a close look at our options.

I don't know if this is directly contributing to what @camillobruni was seeing with bimodal results in Chrome, but I know there have been some concerns with that as well.

**Comment by bgrins** [comment]
In the meeting today there was consensus to make a change here. There was a concern expressed that splitting this up into one or a couple events per step might be too easy for fast hardware - but the next step is someone testing it out and making a recommendation.

**Comment by bgrins** [comment]
FYI - Julien is going to be taking a look at this in the next week or so

**Comment by rniwa** [comment]
It appears to me we need to resolve this one or another before we can release the benchmark.

**Comment by bgrins** [comment]
> It appears to me we need to resolve this one or another before we can release the benchmark.

I still think the best option is to just remove the tests, as we've been discussing over the months. These have had consistent issues with noise, and we are actively working on landing tests for much more popular charting and recently updated libraries (for SVG and Canvas, as we discovered in from [our research]( https://docs.google.com/document/d/1-KGxek_9LKOmIVVIZpA9YzR0fJoXKSJUrJ0P2h7GKIY/edit#)). And if we do end up moving forward with something like #156 that adds even more canvas coverage.

I'd rather focus time and attention on getting others out of `tentative` than trying and figure these ones out. @rniwa @flashdesignory what do you think? Should we prepare a PR to remove them?

**Comment by rniwa** [comment]
When you say removing, are you talking about the whole React-Stockcharts suite or specific subtests?

I tend to agree that the current noise level in Chrome's results leaves this suite rather unsuitable to be included in the final benchmark in its current form. I'm fine with deleting it if we're adding more charting / React content elsewhere.

**Comment by bgrins** [comment]
> When you say removing, are you talking about the whole React-Stockcharts suite or specific subtests?

I mean the whole suite

**Comment by rniwa** [comment]
> > When you say removing, are you talking about the whole React-Stockcharts suite or specific subtests?
> 
> I mean the whole suite

Okay, like I said above, I think I'm fine removing it. We've got a lot of other good contents already.

**Comment by julienw** [comment]
I'd still like to look whether we can make it more stable by mocking rAF. But I won't be able to look before Tuesday.

**Comment by bgrins** [comment]
> I'd still like to look whether we can make it more stable by mocking rAF. But I won't be able to look before Tuesday.

Even if we can make them more stable with the mocked rAF I'm not sure it makes sense to bring them in based on our coverage with more popular charting libraries and other canvas/svg content. I'd like to hear from Thorsten as well, but if you want to take a look at stability next week we can wait to make a decision until then.

**Comment by flashdesignory** [comment]
In general I'm ok with dropping react stockcharts, but I also want to give Julien enough time to do his thing.
Let's decide during our sync on Wednesday?

**Comment by julienw** [comment]
My opinion is that there is value in having a SVG+React workload. The current React-Stockcharts-SVG provides that.
It looks like that with the `rAF = setTimeout` hack I can get stable runs.
In a future version of speedometer it would still be better to replace it with something based on a maintained library such as recharts, but for SP3 I believe we can use this one.

We can remove React-Stockcharts-Canvas though.

**Comment by rniwa** [comment]
@bgrins : why did you re-open this issue given the workload has been removed in https://github.com/WebKit/Speedometer/commit/36a320c98e6e2d6d5bab234552624527486aa6d3?

**Comment by bgrins** [comment]
I don't know why I reopened this, I think it was an accident

**Comment by nullhook** [comment]
I was deeply looking into this workload and React's 16.2.0 (old) reconciler.
  
For ex, `ZoomTheChart` work seems heavily attributed towards Sync because the work fires many wheel events and calls `setState` inside the wheel handler and React's internals seem to flush this instantly rather than batching. I'm not sure if the newer React's internals fixes this?

Also, something layout thrashes in this path.

Since wheel events are continuous, a burst of them would normally batch into a single render. However, due to poor choices made in userland, I wonder how much of it is redundant work.
